description: Playbook to handle incident triggered from PANW Iot (Zingbox) UI to send
  Vulnerability to ServiceNow.
id: Export Single Vulnerability to ServiceNow - PANW IoT 3rd Party Integration
inputs: []
name: Export Single Vulnerability to ServiceNow - PANW IoT 3rd Party Integration
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 55b562fd-adcf-49fc-8058-953f50028ae8
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 55b562fd-adcf-49fc-8058-953f50028ae8
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: ServiceNow v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 5a7ab21d-cb64-4562-8c4d-dfd257fefb63
      iscommand: false
      name: Is ServiceNow available
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 5a7ab21d-cb64-4562-8c4d-dfd257fefb63
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      integrationName:
        simple: servicenow
      message:
        simple: Servicenow instance is not enabled
      playbookName:
        simple: Export Single Vulnerability to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: disabled
      type:
        simple: vulnerability
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: daeb1f50-f920-4fc8-8029-64f4b49c39a2
      iscommand: true
      name: send disabled status back to panw iot
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: daeb1f50-f920-4fc8-8029-64f4b49c39a2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 5e8dd212-4d39-4eb4-8354-74717742ac85
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 5e8dd212-4d39-4eb4-8354-74717742ac85
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "4":
    continueonerror: true
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      assetID:
        simple: ${incident.correlation_id}
      assetType:
        simple: Vulnerability
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: For a given a asset ID (alert-id, vulnerability-id or mac-address)
        returns the asset details.
      id: a3a069af-9656-4de1-891d-5c6d64927d00
      iscommand: true
      name: get single vulnerability instance
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-get-single-asset
      type: regular
      version: -1
    taskid: a3a069af-9656-4de1-891d-5c6d64927d00
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 380
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      "no":
      - "6"
      "yes":
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${PanwIot3rdParty.SingleAsset}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: ee1d48b8-114b-4f3c-8e06-f9e8219060c3
      iscommand: false
      name: Does the vulnerability exist
      script: Exists
      type: condition
      version: -1
    taskid: ee1d48b8-114b-4f3c-8e06-f9e8219060c3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      integrationName:
        simple: servicenow
      message:
        simple: Cannot find vulnerability with zb_ticketid ${incident.correlation_id}
      playbookName:
        simple: Export Single Vulnerability to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
      type:
        simple: vulnerability
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: c2872bf8-257a-4347-80dd-9c56b16a8543
      iscommand: true
      name: send error status back to panw iot
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: c2872bf8-257a-4347-80dd-9c56b16a8543
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 7c66b977-3105-4738-85ab-41cf340401af
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 7c66b977-3105-4738-85ab-41cf340401af
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "8":
    continueonerror: true
    id: "8"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      asset:
        complex:
          accessor: SingleAsset
          root: PanwIot3rdParty
          transformers:
          - args:
              index:
                value:
                  simple: "0"
            operator: atIndex
      assetList:
        simple: ${PanwIot3rdParty.SingleAsset}
      assetType:
        simple: Vulnerability
      incident:
        simple: ${incident}
      metadata: {}
      metadata1:
        simple: ${incident}
      outputFormat:
        simple: ServiceNow
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: For a given asset (alert, device, vuln) converts it to 3rd party
        format.
      id: 0ae475ec-26bb-42fe-86de-c6fded4f8850
      iscommand: true
      name: convert vulnerability to ServiceNow format
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-convert-assets-to-external-format
      type: regular
      version: -1
    taskid: 0ae475ec-26bb-42fe-86de-c6fded4f8850
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 720
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    nexttasks:
      "no":
      - "12"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: c3290332-2f63-4e28-8ca6-341d93f2cfdf
      iscommand: false
      name: isError
      script: isError
      type: condition
      version: -1
    taskid: c3290332-2f63-4e28-8ca6-341d93f2cfdf
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 695,
          "y": 895
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      integrationName:
        simple: servicenow
      message:
        simple: Cannot convert vulnerability to servicenow data format
      playbookName:
        simple: Export Single Vulnerability to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
      type:
        simple: vulnerability
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: ef5e9c29-97ab-45a3-886d-11c82d6b7096
      iscommand: true
      name: send error status back to panw iot
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: ef5e9c29-97ab-45a3-886d-11c82d6b7096
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
  "11":
    id: "11"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: dfae67e9-3fa9-40a3-8db3-f28ea7333a1f
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: dfae67e9-3fa9-40a3-8db3-f28ea7333a1f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
  "12":
    continueonerror: true
    id: "12"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      custom_fields: {}
      fields:
        simple: ${PanwIot3rdParty.VulnerabilityServiceNow}
      input_display_value: {}
      table_name:
        simple: u_zingbox_alerts_vulnerablilty_incident
    separatecontext: false
    skipunavailable: false
    task:
      brand: ServiceNow v2
      description: Creates a new record in the specified ServiceNow table.
      id: 9a911245-3731-4166-80a5-ee73b04c0c0d
      iscommand: true
      name: servicenow-create-record
      script: ServiceNow v2|||servicenow-create-record
      type: regular
      version: -1
    taskid: 9a911245-3731-4166-80a5-ee73b04c0c0d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1070
        }
      }
  "13":
    id: "13"
    ignoreworker: false
    nexttasks:
      "no":
      - "16"
      "yes":
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 1e9c002b-bc0d-42f6-8fba-97e254d2c7ea
      iscommand: false
      name: isError
      script: isError
      type: condition
      version: -1
    taskid: 1e9c002b-bc0d-42f6-8fba-97e254d2c7ea
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1245
        }
      }
  "14":
    id: "14"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      integrationName:
        simple: servicenow
      message:
        simple: Failed to send vulnerability to ServiceNow
      playbookName:
        simple: Export Single Vulnerability to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
      type:
        simple: vulnerability
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 41004cc5-f34a-48a9-86e2-ae95cd465330
      iscommand: true
      name: send error status back to panw iot
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 41004cc5-f34a-48a9-86e2-ae95cd465330
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1420
        }
      }
  "15":
    id: "15"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 78dcd27a-6abd-43eb-87b1-b7bc5460a5fb
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 78dcd27a-6abd-43eb-87b1-b7bc5460a5fb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1595
        }
      }
  "16":
    id: "16"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      integrationName:
        simple: servicenow
      message:
        simple: Success to send vulnerability instance zb_ticket id ${incident.correlation_id}
          to ServiceNow
      playbookName:
        simple: Export Single Vulnerability to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: success
      type:
        simple: vulnerability
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 233e761a-73ad-4741-8d4d-64549fbad7ac
      iscommand: true
      name: send success status back to panw iot
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 233e761a-73ad-4741-8d4d-64549fbad7ac
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1420
        }
      }
  "17":
    id: "17"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 036c7dc0-05f8-488c-8a1c-e78eea7c0899
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 036c7dc0-05f8-488c-8a1c-e78eea7c0899
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1595
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1640,
        "width": 1455,
        "x": 50,
        "y": 50
      }
    }
  }

fromversion: 6.0.0
tests:
- No tests (auto formatted)
