description: Playbook to handle incident triggered from PANW Iot (Zingbox) UI to send
  Vulnerability to SIEM.
id: Export Single Vulnerability to SIEM - PANW IoT 3rd Party Integration
inputs: []
name: Export Single Vulnerability to SIEM - PANW IoT 3rd Party Integration
outputs:
- contextPath: incident
  description: This playbook is invoked via the incident type "PANW IoT 3rd Party
    SIEM Integration - Vulnerability"
  type: unknown
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1bad57f9-4b78-4d0e-8178-7b2d945b636a
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 1bad57f9-4b78-4d0e-8178-7b2d945b636a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    id: "1"
    ignoreworker: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Syslog Sender
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 112b8daf-c8dc-4c37-8faf-de37b32bfc53
      iscommand: false
      name: IsIntegrationAvailable
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 112b8daf-c8dc-4c37-8faf-de37b32bfc53
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
  "2":
    continueonerror: true
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      integrationName:
        simple: siem
      message:
        simple: Syslog Sender (SIEM) instance is not enabled
      playbookName:
        simple: Export Single Vulnerability to SIEM - PANW IoT 3rd Party Integration
          to SIEM
      status:
        simple: disabled
      type:
        simple: vulnerability
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 21016b18-61bf-4a76-8d7f-d63b5f240690
      iscommand: true
      name: panw-iot-3rd-party-report-status-to-panw
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 21016b18-61bf-4a76-8d7f-d63b5f240690
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 100,
          "y": 410
        }
      }
  "3":
    continueonerror: true
    id: "3"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      assetID:
        simple: ${incident.zb_ticketid}
      assetType:
        simple: Vulnerability
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: For a given a asset ID (alert-id, vulnerability-id or mac-address)
        returns the asset details.
      id: 9344a410-a3b7-4242-81dd-606c82b7432c
      iscommand: true
      name: panw-iot-3rd-party-get-single-asset
      script: '|||panw-iot-3rd-party-get-single-asset'
      type: regular
      version: -1
    taskid: 9344a410-a3b7-4242-81dd-606c82b7432c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 660,
          "y": 400
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    nexttasks:
      "no":
      - "5"
      "yes":
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 6f730d53-b67a-46b6-82e1-982508336403
      iscommand: false
      name: isError
      script: isError
      type: condition
      version: -1
    taskid: 6f730d53-b67a-46b6-82e1-982508336403
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 660,
          "y": 570
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      "no":
      - "8"
      "yes":
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${PanwIot3rdParty.SingleAsset}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: fe731bcc-e441-4db6-8b3c-a1fc5b1371aa
      iscommand: false
      name: Exists
      script: Exists
      type: condition
      version: -1
    taskid: fe731bcc-e441-4db6-8b3c-a1fc5b1371aa
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 880,
          "y": 750
        }
      }
  "6":
    continueonerror: true
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      integrationName:
        simple: siem
      message:
        simple: Failed to get Vulnerability (${incident.zb_ticketid}) from IoT cloud.
      playbookName:
        simple: Export Single Vulnerability to SIEM - PANW IoT 3rd Party Integration
          to SIEM
      status:
        simple: error
      type:
        simple: alert
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: e6f696eb-ae04-44e9-85b3-023d541e09bb
      iscommand: true
      name: panw-iot-3rd-party-report-status-to-panw
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: e6f696eb-ae04-44e9-85b3-023d541e09bb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 410,
          "y": 760
        }
      }
  "7":
    continueonerror: true
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      assetList:
        simple: ${PanwIot3rdParty.SingleAsset}
      assetType:
        simple: Vulnerability
      outputFormat:
        simple: SIEM
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: For a given asset (alert, device, vuln) converts it to 3rd party
        format.
      id: c65c35da-b12b-445f-84b4-1826226e46c4
      iscommand: true
      name: panw-iot-3rd-party-convert-assets-to-external-format
      script: '|||panw-iot-3rd-party-convert-assets-to-external-format'
      type: regular
      version: -1
    taskid: c65c35da-b12b-445f-84b4-1826226e46c4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1110,
          "y": 930
        }
      }
  "8":
    continueonerror: true
    id: "8"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      integrationName:
        simple: siem
      message:
        simple: No Vulnerability found with given ID  (${incident.zb_ticketid}).
      playbookName:
        simple: Export Single Vulnerability to SIEM - PANW IoT 3rd Party Integration 
      status:
        simple: error
      type:
        simple: vulnerability
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 1cad0a74-aafc-4d77-8ed5-d048a91c5781
      iscommand: true
      name: panw-iot-3rd-party-report-status-to-panw
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 1cad0a74-aafc-4d77-8ed5-d048a91c5781
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 640,
          "y": 930
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    nexttasks:
      "no":
      - "11"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${PanwIot3rdParty.VulnerabilityCEFSyslogs}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 46e69c4c-bc61-46ad-8e35-d8a16c7f5736
      iscommand: false
      name: Exists
      script: Exists
      type: condition
      version: -1
    taskid: 46e69c4c-bc61-46ad-8e35-d8a16c7f5736
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1110,
          "y": 1090
        }
      }
  "10":
    continueonerror: true
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      address: {}
      facility: {}
      level: {}
      message:
        simple: ${PanwIot3rdParty.VulnerabilityCEFSyslogs}
      port: {}
      protocol: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Syslog Sender
      description: Sends a message to Syslog.
      id: 2befa0e9-6239-44c3-8894-55314c0fe5f5
      iscommand: true
      name: syslog-send
      script: '|||syslog-send'
      type: regular
      version: -1
    taskid: 2befa0e9-6239-44c3-8894-55314c0fe5f5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1350,
          "y": 1260
        }
      }
  "11":
    continueonerror: true
    id: "11"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      integrationName:
        simple: siem
      message:
        simple: Vulnerability ID  (${incident.zb_ticketid}) not valid for CEF conversion.
      playbookName:
        simple: Export Single Vulnerability to SIEM - PANW IoT 3rd Party Integration
          to SIEM
      status:
        simple: error
      type:
        simple: vulnerability
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: c4858660-2467-4186-8850-5206e2353ec0
      iscommand: true
      name: panw-iot-3rd-party-report-status-to-panw
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: c4858660-2467-4186-8850-5206e2353ec0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 870,
          "y": 1270
        }
      }
  "12":
    continueonerror: true
    id: "12"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      integrationName:
        simple: siem
      message:
        simple: Successfully sent Vulnerability (${incident.zb_ticketid}) to SIEM
      playbookName:
        simple: Export Single Vulnerability to SIEM - PANW IoT 3rd Party Integration
          to SIEM
      status:
        simple: success
      type:
        simple: vulnerability
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: 887e93a2-644b-4f93-824b-9bcdcabf2ac2
      iscommand: true
      name: panw-iot-3rd-party-report-status-to-panw
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: 887e93a2-644b-4f93-824b-9bcdcabf2ac2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1350,
          "y": 1460
        }
      }
  "13":
    id: "13"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: d95b4a06-b751-4c2a-89a3-7f36a25370a6
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: d95b4a06-b751-4c2a-89a3-7f36a25370a6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 120,
          "y": 1590
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "1_3_yes": 0.74
    },
    "paper": {
      "dimensions": {
        "height": 1635,
        "width": 1630,
        "x": 100,
        "y": 50
      }
    }
  }
fromversion: 6.0.0
tests:
- No tests (auto formatted)
