description: Playbook to handle incident triggered from PANW Iot (Zingbox) UI to send
  Alert to ServiceNow.
id: Export Single Alert to ServiceNow - PANW IoT 3rd Party Integration
inputs: []
name: Export Single Alert to ServiceNow - PANW IoT 3rd Party Integration
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 45a4ab5b-a09e-401d-8e6b-7a079f9f28e3
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 45a4ab5b-a09e-401d-8e6b-7a079f9f28e3
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    id: "1"
    ignoreworker: false
    nexttasks:
      "no":
      - "3"
      "yes":
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: ServiceNow v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: e5141f5e-f5fc-4ab6-89f7-3758ee54ad8a
      iscommand: false
      name: Is ServiceNow available
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: e5141f5e-f5fc-4ab6-89f7-3758ee54ad8a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "2":
    continueonerror: true
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      assetID:
        complex:
          root: incident
          transformers:
          - args:
              field:
                value:
                  simple: correlation_id
            operator: getField
      assetType:
        simple: Alert
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: For a given a asset ID (alert-id, vulnerability-id or mac-address)
        returns the asset details.
      id: 80fb8a12-7a20-4b08-8061-d8c64521eb45
      iscommand: true
      name: get single alert instance
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-get-single-asset
      type: regular
      version: -1
    taskid: 80fb8a12-7a20-4b08-8061-d8c64521eb45
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      integrationName:
        simple: servicenow
      message:
        simple: ServiceNow instance is not enabled
      playbookName:
        simple: Export Single Alert to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: disabled
      type:
        simple: alert
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 92c5c696-a6dd-4d4e-8956-5d9a6e01f42b
      iscommand: true
      name: send disabled status back to panw iot
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 92c5c696-a6dd-4d4e-8956-5d9a6e01f42b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 2a6874fc-5337-4e4f-853a-8685ecb885cd
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 2a6874fc-5337-4e4f-853a-8685ecb885cd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "5":
    continueonerror: true
    id: "5"
    ignoreworker: false
    nexttasks:
      "no":
      - "7"
      "yes":
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${PanwIot3rdParty.SingleAsset}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: d127755d-195c-47d1-8975-0176ea192f31
      iscommand: false
      name: Does alert instance exist
      script: Exists
      type: condition
      version: -1
    taskid: d127755d-195c-47d1-8975-0176ea192f31
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "6":
    continueonerror: true
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      asset:
        complex:
          accessor: SingleAsset
          root: PanwIot3rdParty
          transformers:
          - args:
              index:
                value:
                  simple: "0"
            operator: atIndex
      assetList:
        simple: ${PanwIot3rdParty.SingleAsset}
      assetType:
        simple: Alert
      incident:
        simple: ${incident}
      metadata: {}
      metadata1:
        simple: ${incident}
      outputFormat:
        simple: ServiceNow
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: For a given asset (alert, device, vuln) converts it to 3rd party
        format.
      id: 8430282e-0f80-406e-8d51-6f3b6a56a1a8
      iscommand: true
      name: convert alert to ServiceNow format
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-convert-assets-to-external-format
      type: regular
      version: -1
    taskid: 8430282e-0f80-406e-8d51-6f3b6a56a1a8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 720
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      integrationName:
        simple: servicenow
      message:
        simple: Failed to get alert instance zb_ticket id ${incident.correlation_id}
      playbookName:
        simple: Export Single Alert to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
      type:
        simple: alert
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 77cde86b-41cb-489d-8d48-493c452ac501
      iscommand: true
      name: send error status back to panw iot
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 77cde86b-41cb-489d-8d48-493c452ac501
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 72beae67-4104-4242-8db7-27b99ea30c85
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 72beae67-4104-4242-8db7-27b99ea30c85
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "9":
    continueonerror: true
    id: "9"
    ignoreworker: false
    nexttasks:
      "no":
      - "12"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 22c1bb77-8b4d-48c3-8c72-80d180fd68e4
      iscommand: false
      name: isError
      script: isError
      type: condition
      version: -1
    taskid: 22c1bb77-8b4d-48c3-8c72-80d180fd68e4
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 695,
          "y": 895
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      integrationName:
        simple: servicenow
      message:
        simple: Failed to convert alert to servicenow format
      playbookName:
        simple: Export Single Alert to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
      type:
        simple: alert
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: aafb5499-9785-4d88-8f77-bf72c9354616
      iscommand: true
      name: send error status back to panw iot
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: aafb5499-9785-4d88-8f77-bf72c9354616
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
  "11":
    id: "11"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 21b63140-ba40-43ce-869f-03c6eeacf056
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 21b63140-ba40-43ce-869f-03c6eeacf056
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
  "12":
    continueonerror: true
    id: "12"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      custom_fields: {}
      fields:
        simple: ${PanwIot3rdParty.AlertServiceNow}
      input_display_value: {}
      table_name:
        simple: u_zingbox_alerts_vulnerablilty_incident
    separatecontext: false
    skipunavailable: false
    task:
      brand: ServiceNow v2
      description: Creates a new record in the specified ServiceNow table.
      id: 3eb4fb10-7199-4d99-8082-71a1d0b9bc1c
      iscommand: true
      name: servicenow-create-record
      script: ServiceNow v2|||servicenow-create-record
      type: regular
      version: -1
    taskid: 3eb4fb10-7199-4d99-8082-71a1d0b9bc1c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1070
        }
      }
  "13":
    id: "13"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      integrationName:
        simple: servicenow
      message:
        simple: Success to send alert instance zb_ticket id ${incident.correlation_id}
          to ServiceNow
      playbookName:
        simple: Export Single Alert to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: success
      type:
        simple: alert
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 1754161d-dcb9-4240-8b97-9bc7008fb008
      iscommand: true
      name: send success status back to panw iot
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 1754161d-dcb9-4240-8b97-9bc7008fb008
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1420
        }
      }
  "14":
    id: "14"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: f5932f37-25bb-4ddc-8bc0-78460a90ae9a
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: f5932f37-25bb-4ddc-8bc0-78460a90ae9a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1595
        }
      }
  "15":
    continueonerror: true
    id: "15"
    ignoreworker: false
    nexttasks:
      "no":
      - "13"
      "yes":
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 57cf6efe-fa45-4b9f-8a03-6bccbef21bf8
      iscommand: false
      name: isError
      script: isError
      type: condition
      version: -1
    taskid: 57cf6efe-fa45-4b9f-8a03-6bccbef21bf8
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1245
        }
      }
  "16":
    id: "16"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      integrationName:
        simple: servicenow
      message:
        simple: Failed to create record in servicenow table
      playbookName:
        simple: Export Single Alert to ServiceNow - PANW IoT 3rd Party Integration
      status:
        simple: error
      type:
        simple: alert
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto Networks IoT 3rd Party
      description: Sends a status message back to PANW IOT cloud.
      id: 3dcf5eb7-de33-4a12-8561-f4d4156af62b
      iscommand: true
      name: send error status back to panw iot
      script: Palo Alto Networks IoT 3rd Party|||panw-iot-3rd-party-report-status-to-panw
      type: regular
      version: -1
    taskid: 3dcf5eb7-de33-4a12-8561-f4d4156af62b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1420
        }
      }
  "17":
    id: "17"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: b7824a6c-9174-4ff6-8259-67fb67a91ae3
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: b7824a6c-9174-4ff6-8259-67fb67a91ae3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1595
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1640,
        "width": 1455,
        "x": 50,
        "y": 50
      }
    }
  }

fromversion: 6.0.0
tests:
- No tests (auto formatted)
